// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWEboj36tn6Ma5HDNkeO3xPAnMzDd7BU',
    appId: '1:675448118426:android:0434e205b91c7276b59323',
    messagingSenderId: '675448118426',
    projectId: 'finstagram-udemy-6305e',
    databaseURL: 'https://finstagram-udemy-6305e-default-rtdb.firebaseio.com',
    storageBucket: 'finstagram-udemy-6305e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3ENdhN0CBr8VSF3zG9X_E_JmavwBnow',
    appId: '1:675448118426:ios:41edf193d6f8907ab59323',
    messagingSenderId: '675448118426',
    projectId: 'finstagram-udemy-6305e',
    databaseURL: 'https://finstagram-udemy-6305e-default-rtdb.firebaseio.com',
    storageBucket: 'finstagram-udemy-6305e.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );
}
